### PR TITLE
203 update and review codeowners and maintainersmd file

### LINKED ISSUE #203: Update and review CODEOWNERS and MAINTAINERS.md file
**Problem description**

Update CODEOWERNS and MAINTAINERS.md as per points 3 and 7 of https://github.com/camaraproject/Governance/issues/134
and ensure that all Maintainer and Codeowner are accepted the invite into the CAMARA GitHub organization.

**Expected action**

Create PR for the updates.
Review the current Maintainer list.

**Additional context**

### PR DESCRIPTION
**Pull request by hdamker**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

See #203 

#### Which issue(s) this PR fixes:

Fixes #203

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
LGTM

**Review by jlurien — APPROVED** [review]
Regarding the Maintainers list, the current one does not reflect the people actually involved in the subproject, but I guess that is beyond the purpose of the PR.

**Comment by hdamker** [comment]
> Regarding the Maintainers list, the current one does not reflect the people actually involved in the subproject, but I guess that is beyond the purpose of the PR.

@jlurien Half/half: the PR is also meant to trigger the review of the list. But yes, the actual changes could or even should be done in separate PRs.

**Comment by jlurien** [comment]
> > Regarding the Maintainers list, the current one does not reflect the people actually involved in the subproject, but I guess that is beyond the purpose of the PR.
> 
> @jlurien Half/half: the PR is also meant to trigger the review of the list. But yes, the actual changes could or even should be done in separate PRs.

Understood. Device Location has a quite stable group of contributors but it's not the same people as in the list.

**Pull request merged**
