### PR TITLE
Added Tests

### PR DESCRIPTION
**Pull request by questsin**
#### What type of PR is this?

* tests - As a requirement from commonalities agreed on guideline, there need to be test case contributions to a subproject. You can find the details under point (5) of API-Readiness-Checklist.md

#### What this PR does / why we need it:

As a provider implementor from 5GFF and Rogers Communications, contributions from our Compliance and Conformance test bed fulfilling the minimum criteria of readiness w.r.t API test cases and documentation, including in the Gherkin Style. 
This can be easily translated to any language and framework of the day. Its just a start, but based on our real-life implementations and inspired by TMForum conformance and compliance tests in the same framework. 
It's also self-contained and includes all the bells and whistles, batteries included, and can run anywhere 😀

### CODE REVIEW

**Comment by mdomale** [comment]
@questsin : Kindly refer to the commonalities agreed guideline for making test case contributions to a subproject. You can find the details under point (5) of [API-Readiness-Checklist.md](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-Readiness-Checklist.md)

**Comment by questsin** [comment]
As far as I know, this repo does not follow point 5 of that guide as no Gherkin or test cases are provided as required. This is an attempt to remedy this.

**Comment by jlurien** [comment]
Hi @questsin,

Thanks for your interest in the WG work. We have not started yet a conversation within this WG on how to accommodate test cases, but an HTML file as part of the documentation is not the way to manage them. 

Before submitting a new PR, we ask contributors to fill a new issue explaining the requirement and introduce some initial proposal, if any. From there, other contributors can comment on it, and issue may also be discussed into our bi-weekly meetings . When there is some early consensus on the necessity and the approach, a PR is to be created.

I suggest you to open a new issue and start with some proposal for the Gherkin scenarios that you are considering. Then, we can review on how to proceed, and discuss the folder structure.

**Comment by jlurien** [comment]
Closing this PR once it has been moved to issue

**Pull request closed without merging**
