### PR TITLE
geofencing: Alignment of errors with Commonalities 

### LINKED ISSUE #222: Align Geofencing with guidelines for error scenarios
**Problem description**
Current version still does not follow the recent guidelines.

**Possible evolution**
Align codes and examples as indicated in:

https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml

**Additional context**
Related issues for:

- Location retrieval #219
- Location verification #214

### PR DESCRIPTION
**Pull request by maxl2287**
#### What type of PR is this?

Add one of the following kinds:

* enhancement/feature

#### What this PR does / why we need it:
Alignement of errors according to Commonalities guideline.

#### Which issue(s) this PR fixes:

Fixes #222 

#### Changelog input

```
 release-note

- Aligned error code list with Commonalities for geofencing API
```

### CODE REVIEW

**Review by bigludo7 — DISMISSED** [review]
LGTM

**Review by jlurien — COMMENTED** [review]
I would reconsider adding explicit mention to errors such as 405, 406, 409, 410, 412, 415, 429, which are not part of the core of the API logic, and may be implemented by previous layers (access control, etc). This has been also discussed in [QOD](https://github.com/camaraproject/QualityOnDemand/issues/305)

**Review by bigludo7 — APPROVED** [review]
Thanks Max
Look good for me.

**Comment by maxl2287** [comment]
@akoshunyadi @jlurien @bigludo7 same discussion here like in https://github.com/camaraproject/DeviceStatus/pull/193#issuecomment-2247598250

We need now a clear decission:
Either we use all of the errorcodes from the template (incl. e.g. HTTP-410 or just the API relevant codes.)

Wdyt?

**Review by jlurien — APPROVED** [review]
LGTM. IMO we should restrict the codes to the relevant ones for the spec, but the specific list should be discussed in Commonalities and the guidelines and artifacts be adjusted.

**Pull request merged**
