### PR TITLE
Github templates

### LINKED ISSUE #63: Adding template for issue & PR
@rartych may I ask you to do some magic to integrate CAMARA template for issue and PR for our project ?

I'm not familiar with this operation :)

Thanks

### PR DESCRIPTION
**Pull request by rartych**
#### What type of PR is this?

* subproject management

#### Which issue(s) this PR fixes:

Fixes #63

#### Changelog input

```
Added Github templates for Issues and PRs

```

#### Additional documentation 

[Templates How-to](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Issue%20and%20PR%20template%20Howto.md)

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
Thanks Rafal !

**Comment by bigludo7** [comment]
@jlurien I forget to mention this point yesterday but this is for alignment with Issue/PR CAMARA template. Thanks a lot @rartych  for the quick contribution.

**Comment by rartych** [comment]
In order to fully support automatic issue labeling 2 labels need to be added (created): correction , subproject management.

(In Identity and Consent subprojects the label colors were set to  #DB2F1F and  #515C8B respectively)

**Review by jlurien — APPROVED** [review]
Thanks

**Comment by jlurien** [comment]
> #515C8B

Created

**Pull request merged**
