### PR TITLE
Prepare release 1.1 for location-verification

### PR DESCRIPTION
**Pull request by jlurien**
#### What type of PR is this?

* correction
* subproject management

#### What this PR does / why we need it:

Prepare location-verification for r1.1
Some fixes after review

Before creating the r1.1 release we have to:

Merge the pending PRs for geofencing (maybe with the exception of the test plan)
Create a PR for geofencing adjusting versions for r1.1
Merge the PR for location-retrieval for r1.1
Merge this PR for location-verification
Create a new PR with README/CHANGELOG for r1.1 and versions updated

#### Special notes for reviewers:

Same as https://github.com/camaraproject/DeviceLocation/pull/238 which was merged by mistake and reverted

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
LGTM

**Comment by hdamker** [comment]
@jlurien related to my comment within #235 would be my proposal to split this PR into two different ones:

a) a PR with the identified changes on location-verification YAML and test definition file, but keeping the version in "wip"
b) a "release PR" for the repository with all there APIs, which will be kept open until all last changes on the APIs are done, that will will set the API Version across all YAMLs.

Doing a) before b) has the purpose that reviewers can see the final content which will be released in main and there are no side effects on code by the release PR.

**Comment by jlurien** [comment]
I will save CHANGELOG and README for the final PR for r1.1.

**Comment by jlurien** [comment]
@maxl2287 please review and eventually approve this, as Ludovic is already on holidays. I applied last @hdamker suggestions to separate the latest changes in location-verification from the PR fo r1.1, which I'll prepare once we have the assets for the 3 APIs ready

**Review by maxl2287 — APPROVED** [review]
LGTM

**Pull request merged**
