### PR TITLE
fix/ location-verification: remodel-Area-inheritance

### LINKED ISSUE #72: Remodel Area as inheritance
**Problem description**

Area uses a polymorphic model (oneOf)

**Expected behavior**

Guidelines favor inheritance (allOf) 

**Alternative solution**

Remodel Area a base class and Circle as child

**Additional context**

### PR DESCRIPTION
**Pull request by jlurien**
#### What type of PR is this?

* correction

#### What this PR does / why we need it:

* Remodel Area as inheritance model with allOf

#### Which issue(s) this PR fixes:

Fixes #72 

#### Special notes for reviewers:

type moved to base class

#### Changelog input

n/a

#### Additional documentation 

n/a

### CODE REVIEW

**Review by bigludo7 — COMMENTED** [review]
Did same work for the raw location and seems were aligned - good if you can take a look to make sure about this alignment.

3 minor requests for your consideration:
- Instead of `type `I renamed the attribute as `areaType`
- Instead of `location `(line 126) could we use `center `as we describe a circle.
- For same reason instead of `accuracy  `could we rename the attribute `radius`.

This more explicit for the API consumer.

**Comment by jlurien** [comment]
> Did same work for the raw location and seems were aligned - good if you can take a look to make sure about this alignment.
> 
> 3 minor requests for your consideration:
> 
> * Instead of `type `I renamed the attribute as `areaType`

OK, indeed I was already considering this name, just in case we have for example some `codeType` or similar in the future.
 
> * Instead of `location `(line 126) could we use `center `as we describe a circle.
> * For same reason instead of `accuracy  `could we rename the attribute `radius`.
> 

Modelling areas as geometrical figures, it could make sense. Originally it was meant to represent an specific target point with some accuracy, which could be understood as the device more likely to be close to the center. If we add other type of areas, as code areas, is just another area.

I will ask internally for other opinions.

> This more explicit for the API consumer.

**Comment by jlurien** [comment]
@bigludo7 I have renamed the Area and Circle properties with your suggestions

**Review by bigludo7 — APPROVED** [review]
Look good for me

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
