### PR TITLE
Doc: Embed documentation into API spec

### PR DESCRIPTION
**Pull request by jlurien**
#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

- Ad doc to `info.description` section
- Remove legacy doc markdown file

#### Which issue(s) this PR fixes:

Comply with Commonalities guidelines.

#### Special notes for reviewers:

Review that wording is correct. Suggest clarifications or improvements

#### Changelog input

```
API doc is now embedded into API spec 

```

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
With a proposal change to add bullet points.

**Review by alpaycetin74 — COMMENTED** [review]
May I ask 2 questions:

- Do we not intend to define how the match rate should be calculated? Our definition seems open to interpretation to the implementer.   
- Why is the match partial if the network can provide "higher" accuracy ? Do you mean the numerical value in the response is larger ? This is actually "worse" accuracy than requested. This may be misunderstood.
Thank you.

**Comment by jlurien** [comment]
> May I ask 2 questions:
> 
> * Do we not intend to define how the match rate should be calculated? Our definition seems open to interpretation to the implementer.
> * Why is the match partial if the network can provide "higher" accuracy ? Do you mean the numerical value in the response is larger ? This is actually "worse" accuracy than requested. This may be misunderstood.
>   Thank you.

We should try to agree on a common understanding and implementation. Indeed, there is an open discussion on how to approach the situation with worse accuracy by the network (higher value here is really the opposite). We may open a dedicate discussion for implementation guidelines, and for the time being I'll rephrase the current description to make it more neutral.

**Review by bigludo7 — APPROVED** [review]
LGFM

**Pull request merged**
