### PR TITLE
Introducing corrections for yamllint

### PR DESCRIPTION
**Pull request by rartych**
#### What type of PR is this?

Add one of the following kinds:
* correction

#### What this PR does / why we need it:
While preparing PR for linting rules, it occurred that `yamllint` produces  large number of errors (mainly trailing spaces).
I propose to merge this changes before introducing the linting rules workflows configuration, otherwise the errors will be raised by Megalinter.

#### Which issue(s) this PR fixes:

Fixes #

#### Changelog input

```
yaml linting errors cleaned up

```

#### Additional documentation 

```
code/API_definitions/geofencing.yaml
  Error: 6:1 [trailing-spaces] trailing spaces
  Error: 8:1 [trailing-spaces] trailing spaces
  Error: 10:1 [trailing-spaces] trailing spaces
  Error: 11:152 [trailing-spaces] trailing spaces
  Error: 12:1 [trailing-spaces] trailing spaces
  Error: 14:1 [trailing-spaces] trailing spaces
  Error: 16:1 [trailing-spaces] trailing spaces
  Error: 18:1 [trailing-spaces] trailing spaces
  Error: 19:55 [trailing-spaces] trailing spaces
  Error: 21:1 [trailing-spaces] trailing spaces
  Error: 23:1 [trailing-spaces] trailing spaces
  Error: 25:1 [trailing-spaces] trailing spaces
  Error: 27:1 [trailing-spaces] trailing spaces
  Error: 29:1 [trailing-spaces] trailing spaces
  Error: 31:1 [trailing-spaces] trailing spaces
  Error: 33:92 [trailing-spaces] trailing spaces
  Error: 34:1 [trailing-spaces] trailing spaces
  Error: 37:114 [trailing-spaces] trailing spaces
  Error: 38:1 [trailing-spaces] trailing spaces
  Error: 41:1 [trailing-spaces] trailing spaces
  Error: 43:1 [trailing-spaces] trailing spaces
  Error: 44:148 [trailing-spaces] trailing spaces
  Error: 45:63 [trailing-spaces] trailing spaces
  Error: 46:161 [trailing-spaces] trailing spaces
  Error: 54:104 [trailing-spaces] trailing spaces
  Error: 55:1 [trailing-spaces] trailing spaces
  Error: 57:1 [trailing-spaces] trailing spaces
  Error: 58:65 [trailing-spaces] trailing spaces
  Error: 464:1 [trailing-spaces] trailing spaces
  Error: 474:1 [trailing-spaces] trailing spaces
  Error: 476:1 [trailing-spaces] trailing spaces
  Error: 503:28 [trailing-spaces] trailing spaces
  Error: 504:86 [trailing-spaces] trailing spaces
  Error: 505:122 [trailing-spaces] trailing spaces
  Error: 524:126 [trailing-spaces] trailing spaces
  Error: 529:87 [trailing-spaces] trailing spaces
  Error: 530:126 [trailing-spaces] trailing spaces
  Error: 533:29 [trailing-spaces] trailing spaces
  Error: 539:51 [trailing-spaces] trailing spaces
  Error: 540:165 [trailing-spaces] trailing spaces
  Error: 541:102 [trailing-spaces] trailing spaces
  Error: 542:126 [trailing-spaces] trailing spaces
  Error: 543:118 [trailing-spaces] trailing spaces
  Error: 699:1 [trailing-spaces] trailing spaces
  Error: 710:1 [trailing-spaces] trailing spaces
  Error: 721:1 [trailing-spaces] trailing spaces
  Error: 732:1 [trailing-spaces] trailing spaces
  Error: 743:1 [trailing-spaces] trailing spaces
  Error: 754:1 [trailing-spaces] trailing spaces

code/API_definitions/location-retrieval.yaml
  Error: 5:65 [trailing-spaces] trailing spaces
  Error: 9:93 [trailing-spaces] trailing spaces
  Error: 11:84 [trailing-spaces] trailing spaces
  Error: 15:1 [trailing-spaces] trailing spaces
  Error: 18:92 [trailing-spaces] trailing spaces
  Error: 19:1 [trailing-spaces] trailing spaces
  Error: 20:107 [trailing-spaces] trailing spaces
  Error: 54:65 [trailing-spaces] trailing spaces
  Error: 117:11 [indentation] wrong indentation: expected 12 but found 10
  Error: 216:1 [empty-lines] too many blank lines (3 > 2)
  Error: 224:26 [trailing-spaces] trailing spaces
  Error: 230:1 [trailing-spaces] trailing spaces
  Error: 256:13 [trailing-spaces] trailing spaces
  Error: 263:20 [trailing-spaces] trailing spaces
  Error: 290:16 [trailing-spaces] trailing spaces
  Error: 293:18 [trailing-spaces] trailing spaces
  Error: 298:15 [trailing-spaces] trailing spaces
  Error: 308:1 [trailing-spaces] trailing spaces
  Error: 408:18 [trailing-spaces] trailing spaces

code/API_definitions/location-verification.yaml
  Error: 5:88 [trailing-spaces] trailing spaces
  Error: 11:118 [trailing-spaces] trailing spaces
  Error: 12:1 [trailing-spaces] trailing spaces
  Error: 14:145 [trailing-spaces] trailing spaces
  Error: 18:288 [trailing-spaces] trailing spaces
  Error: 45:65 [trailing-spaces] trailing spaces
  Error: 115:24 [trailing-spaces] trailing spaces
  Error: 127:59 [trailing-spaces] trailing spaces
  Error: 136:102 [trailing-spaces] trailing spaces
  Error: 143:50 [trailing-spaces] trailing spaces
  Error: 160:11 [indentation] wrong indentation: expected 12 but found 10
  Error: 212:16 [trailing-spaces] trailing spaces
  Error: 215:18 [trailing-spaces] trailing spaces
  Error: 220:15 [trailing-spaces] trailing spaces
  Error: 229:25 [trailing-spaces] trailing spaces
  Error: 236:23 [trailing-spaces] trailing spaces
  Error: 339:1 [trailing-spaces] trailing spaces
  Error: 348:83 [trailing-spaces] trailing spaces
```

### CODE REVIEW

**Review by bigludo7 — DISMISSED** [review]
Thank @rartych 
LGTM

**Review by jlurien — COMMENTED** [review]
The versions have to be updated to the next one and -wip.
We have other PRs in progress that will create conflicts with this one. I suggest to merge first  the other ones, sync this one with main and regenerate the fix

**Comment by jlurien** [comment]
@rartych, please you can regenerate this and resolve the conflicts now. Thanks

**Review by jlurien — APPROVED** [review]

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
