### PR TITLE
Latest alignments and fixes for verification and retrieval

### PR DESCRIPTION
**Pull request by jlurien**
#### What type of PR is this?

* correction
* cleanup
* documentation

#### What this PR does / why we need it:

Aligns both APIs between them
Adds note about networkAccessIdentifier not to be used with this version of guidelines
contact info not to be included
license info to be included

#### Which issue(s) this PR fixes:

Fixes #

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by jlurien** [comment]
@maxl2287 please take a look and approve if OK. Please double check if you need to apply some the same fixes to geofencing

**Review by maxl2287 — APPROVED** [review]
LGTM.
Short question: Is this optional device also enforced for subscriptions?

**Comment by maxl2287** [comment]
> LGTM. Short question: Is this optional device also enforced for subscriptions?

Okay on DeviceStatus it's also still inside the subscriptionDetail to be mandatory.

https://github.com/camaraproject/DeviceStatus/blob/f089994491c7aac658e434c05e09873a473e2d68/code/API_definitions/device-roaming-status-subscriptions.yaml#L506C1-L514C17

**Comment by jlurien** [comment]
> LGTM. Short question: Is this optional device also enforced for subscriptions?

No, for geofencing we decided in a past meeting to keep it as required, because it is returned in the response. One consideration we have been discussing in QoD is to remark that the identifiers that are returned for the device in the response must be the same values that were passed as device identifiers in the request (in our case during subscription creation). This is to avoid disclosing unnecessary and potentially sensible info to the client (e.g. receive an IP as identifier and return the phone number of the device)

**Pull request merged**
