### PR TITLE
Create Location Verification API readiness checklist

### LINKED ISSUE #220: Provide API readiness checklist
**Problem description**
To release an API version, an API Sub Project needs to provide the required release assets as specified in the API Readiness Checklist. Source [here](https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreadinesschecklist) §API readiness checklist

The template for the checklist is the [API-Readiness-Checklist.md](https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API-Readiness-Checklist.md) file located in the CAMARA / ReleaseManagement / documentation repository.

**Expected action**
Create md file checklist

**Additional context**
@jlurien @maxl2287  I've created one issue but we'll need 3 files - one for each API - If we prefer to have 3 separate issues I'm fine with it.

### PR DESCRIPTION
**Pull request by jgarciahospital**
#### What type of PR is this?

Add one of the following kinds:

* documentation
* subproject management

#### What this PR does / why we need it:

Checklist in MetaRelase for location-verification API to become stable (v1.0.0) based on current v0.3.0

#### Which issue(s) this PR fixes:

Fixes #220

### CODE REVIEW

**Comment by bigludo7** [comment]
How do you want to progress on this one @jgarciahospital ?
Do we approve it "as i"t and update it with following PR as asset are present? or do you prefer to keep the PR open and update on this one?

**Comment by jgarciahospital** [comment]
> How do you want to progress on this one @jgarciahospital ? Do we approve it "as i"t and update it with following PR as asset are present? or do you prefer to keep the PR open and update on this one?

Good approach, I think we are following different strategy for this file in each API, but it can work. If you can merge, I'll update it now when uploading the requires user story, for instance.

**Review by jlurien — CHANGES_REQUESTED** [review]
This is just the raw template, it has to be filled with the right values for Status and Comments. Moreover:
- wrong file location: move the template to the API Sub Project repository in the home/**code** folder.
- wrong file name: rename the file to include the prefix <API name> plus a dash, it must be:  locatioon-verification-API-Readiness-Checklist.md

Remove also the instructions at the bottom. If the intention of the PR is to just add the templates without filling them, we could create files for the 3 APIs at once.

**Comment by jlurien** [comment]
I will merge the PR so we can then add content to the template in subsequent PRs

**Review by jlurien — APPROVED** [review]

**Pull request merged**
