### PR TITLE
Update location-retrieval.yaml for release candidate

### PR DESCRIPTION
**Pull request by bigludo7**
Prepare PR for location-retrieval release candidate
issue #112 

#### What type of PR is this?

Add one of the following kinds:

* enhancement/feature

#### What this PR does / why we need it:

Prepare release candidate for location-retrieval

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

Not yet ready for merging --> waiting for ipv6 resolution

#### Changelog input

```
 release-note
- Changed version to v0.1.0-rc

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by jlurien — DISMISSED** [review]
LGTM

**Comment by jlurien** [comment]
We can also adjust some misalignments regarding Errors:

* Generic400: Change description and message in example to: "Invalid argument"
* Generic401: Change description and message in example to: "Unauthenticated"
* Generic403: Change description to "Permission denied"

as in https://github.com/camaraproject/DeviceLocation/pull/104/files#diff-

**Review by bigludo7 — COMMENTED** [review]
Aligned error description and message.
@jlurien not sure  to get all request because in  https://github.com/camaraproject/DeviceLocation/pull/104/files we still have message: "Operation not allowed: ..." for 403 for example.

**Review by jlurien — DISMISSED** [review]

**Comment by jlurien** [comment]
> Aligned error description and message. @jlurien not sure to get all request because in https://github.com/camaraproject/DeviceLocation/pull/104/files we still have message: "Operation not allowed: ..." for 403 for example.

Yes, in some cases, the message has a different explanation, but in the corrected cases the difference with the new CODE is more noticiable. I guess we have a lot of variety across the APIs

**Comment by jlurien** [comment]
@bigludo7, please tale a look to the new Device model approved by QoD: https://github.com/camaraproject/DeviceLocation/issues/117

I have already adjusted location-verification.yaml

**Review by bigludo7 — COMMENTED** [review]
Added device definition

**Review by akoshunyadi — APPROVED** [review]

**Review by jlurien — APPROVED** [review]
LGTM

**Pull request merged**
