### PR TITLE
Prepare RC2

### PR DESCRIPTION
**Pull request by jlurien**
#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

Adjust README and CHANGELOG for upcoming release-0.2.0-rc2

### CODE REVIEW

**Comment by jlurien** [comment]
@bigludo7 please, review so I can create the new rc2 before the holiday break

**Comment by jlurien** [comment]
@bigludo7 feel free to merge if approved in my absence. A new release-0.2.0-rc2 with its branch may be created after it.

**Review by nickvenezia — COMMENTED** [review]
Remove  "Location-based advertising, to trigger targeted advertising after verifying the user is in the area of interest."

**Comment by bigludo7** [comment]
> Remove "Location-based advertising, to trigger targeted advertising after verifying the user is in the area of interest."

Hi @nickvenezia - I'm not able to find the sentence you mentioned. Could you please help me to indicate where this sentence is. Thanks

**Comment by nickvenezia** [comment]
@bigludo7 here you go
[https://github.com/camaraproject/DeviceLocation/blob/release-0.2.0-rc/code/API_definitions/location-verification.yaml]

"  Location Verification could be useful in scenarios such as:

    - Fraud protection, to ensure a given user is located in the location area claimed for financial transactions.
    - Verification of GPS coordinates reported by the app on a device, to ensure the GPS was not faked, e.g. for content delivery with regional restrictions.
    - Location-based advertising, to trigger targeted advertising after verifying the user is in the area of interest.
    - Smart mobility (vehicle / bikes renting), to confirm the location of the device and the location of the vehicle/bike to guarantee they are rented correctly"

**Comment by bigludo7** [comment]
> @bigludo7 here you go [https://github.com/camaraproject/DeviceLocation/blob/release-0.2.0-rc/code/API_definitions/location-verification.yaml]
> 
> " Location Verification could be useful in scenarios such as:
> 
> ```
> - Fraud protection, to ensure a given user is located in the location area claimed for financial transactions.
> - Verification of GPS coordinates reported by the app on a device, to ensure the GPS was not faked, e.g. for content delivery with regional restrictions.
> - Location-based advertising, to trigger targeted advertising after verifying the user is in the area of interest.
> - Smart mobility (vehicle / bikes renting), to confirm the location of the device and the location of the vehicle/bike to guarantee they are rented correctly"
> ```

Thanks Nick
As your request is not on the 2 files updated by @jlurien I suggest to tackle your request in a separate Issue and not in this PR. May I ask you to trigger an issue to raise your comment? and then I will move forward with merging this 2 files. Thanks

**Comment by iamdatanick** [comment]
@jlurien  Code line 26 in the YAML

@bigludo7 Would you still like me trigger an issue? 
I thought that had been done when I posted in regards to the documentation?

[
[])]((https://github.com/camaraproject/DeviceLocation/blob/release-0.2.0-rc/code/API_definitions/location-verification.yaml)
openapi: 3.0.3


    Location Verification could be useful in scenarios such as:

    - Fraud protection, to ensure a given user is located in the location area claimed for financial transactions.
    - Verification of GPS coordinates reported by the app on a device, to ensure the GPS was not faked, e.g. for content delivery with regional restrictions.
**_- Location-based advertising, to trigger targeted advertising after verifying the user is in the area of interest._****
    - Smart mobility (vehicle / bikes renting), to confirm the location of the device and the location of the vehicle/bike to guarantee they are rented correctly.

**Comment by bigludo7** [comment]
@iamdatanick No sorry no need for new issue --> you have already posted https://github.com/camaraproject/DeviceLocation/issues/135

I merge this PR and the issue 135 will be managed in another PR. As we have close the RC2 I prefer to wait @jlurien return before to make any yaml update.

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
