### PR TITLE
correction/update-basePath-location-verification

### LINKED ISSUE #59: Differentiate basePaths for APIS for location verification vs location retrieval
Our [current spec](https://github.com/camaraproject/DeviceLocation/blob/main/code/API_definitions/location.yaml) uses `basePath` =  `location`, but we are now [proposing a new API](https://github.com/camaraproject/DeviceLocation/pull/55) within this WG, and as they are separate APIs they must have different `basePath`.
 
Proposal is to rename current one to `location-verification` and the new one could keep just `location`, or even `location-retrieval`, to make it more explicit.

Thoughts, preferences?

### PR DESCRIPTION
**Pull request by jlurien**
#### What type of PR is this?

Add one of the following kinds:
* correction

#### What this PR does / why we need it:

- Rename basePath as `device-location-verification`, and other related rewording, such as scopes
- Added a note to API documentation *.md, as it is already obsolete and it has to be removed when doc is consolidated into API spec.

#### Which issue(s) this PR fixes:

Fixes #59 

#### Special notes for reviewers:

To consider if we choose the currently proposed `device-location-verification` or a shortened version `location-verification`.

#### Changelog input

```
basePath renamed to `device-location-verification`

```

### CODE REVIEW

**Review by bigludo7 — DISMISSED** [review]
Look good for me

**Review by sfnuser — COMMENTED** [review]
@jlurien Would it be better to rename the `location.yaml` also to `location-verification.yaml`?

**Comment by jlurien** [comment]
> @jlurien Would it be better to rename the `location.yaml` also to `location-verification.yaml`?

Totally, I didn't realized that :) Thanks

**Review by sfnuser — APPROVED** [review]
@jlurien Cheers.

**Review by bigludo7 — COMMENTED** [review]
Look good for me

**Comment by jlurien** [comment]
> Look good for me

Thanks, you have to approve again, to be allowed to merge it

**Review by bigludo7 — APPROVED** [review]
LGFM

**Pull request merged**
